#if !defined( __HIDUSAGETYPE_H__)
#define  __HIDUSAGETYPE_H__

#include "Usb.h"

//Reserved
#define RD      0   //Reserved

//Controls
#define LC      11  //Linear Control
#define OOC     12  //On/Off Control
#define MC      13  //Momentary Control
#define OSC     14  //One Shot Control
#define RTC     15  //Re-trigger Control

//Data
#define Sel     21  //Selector (Array)
#define SV      22  //Static Value (Constant, Variable, Absolute)
#define SF      23  //Static Flag (Constant, Variable, Absolute)
#define DV      24  //Dynamic Value (Data, Variable, Absolute)
#define DF      25  //Dynemic Flag (Data, Variable, Absolute)

//Collection
#define NAry    31  //Named Value
#define CA      32  //Application Collection
#define CL      33  //Logical Collection
#define CP      34  //Physical Collection
#define US      35  //Usage Switch
#define UM      36  //Usage Modifier


//Usage(Reserved)
const uint8_t usgtypUsagePageReserved PROGMEM = RD; 

// Generic Desktop Controls Page
const uint8_t usgtypUsagePointer  PROGMEM = CP;
const uint8_t usgtypUsageMouse  PROGMEM = CA;
const uint8_t usgtypUsageJoystick  PROGMEM = CA;
const uint8_t usgtypUsageGamePad  PROGMEM = CA;
const uint8_t usgtypUsageKeyboard  PROGMEM = CA;
const uint8_t usgtypUsageKeypad  PROGMEM = CA;
const uint8_t usgtypUsageMultiAxisController  PROGMEM = CA;
const uint8_t usgtypUsageTabletPCSystemControls  PROGMEM = CA;
const uint8_t usgtypUsageX  PROGMEM = DV;
const uint8_t usgtypUsageY  PROGMEM = DV;
const uint8_t usgtypUsageZ  PROGMEM = DV;
const uint8_t usgtypUsageRx  PROGMEM = DV;
const uint8_t usgtypUsageRy  PROGMEM = DV;
const uint8_t usgtypUsageRz  PROGMEM = DV;
const uint8_t usgtypUsageSlider  PROGMEM = DV;
const uint8_t usgtypUsageDial  PROGMEM = DV;
const uint8_t usgtypUsageWheel  PROGMEM = DV;
const uint8_t usgtypUsageHatSwitch  PROGMEM = DV;
const uint8_t usgtypUsageCountedBuffer  PROGMEM = CL;
const uint8_t usgtypUsageByteCount  PROGMEM = DV;
const uint8_t usgtypUsageMotionWakeup  PROGMEM = OSC;
const uint8_t usgtypUsageStart  PROGMEM = OOC;
const uint8_t usgtypUsageSelect  PROGMEM = OOC;
const uint8_t usgtypUsageVx  PROGMEM = DV;
const uint8_t usgtypUsageVy  PROGMEM = DV;
const uint8_t usgtypUsageVz  PROGMEM = DV;
const uint8_t usgtypUsageVbrx  PROGMEM = DV;
const uint8_t usgtypUsageVbry  PROGMEM = DV;
const uint8_t usgtypUsageVbrz  PROGMEM = DV;
const uint8_t usgtypUsageVno  PROGMEM = DV;
const uint8_t usgtypUsageFeatureNotification  PROGMEM = DV;
const uint8_t usgtypUsageResolutionMultiplier  PROGMEM = DV;
const uint8_t usgtypUsageSystemControl  PROGMEM = CA;
const uint8_t usgtypUsageSystemPowerDown  PROGMEM = OSC;
const uint8_t usgtypUsageSystemSleep  PROGMEM = OSC;
const uint8_t usgtypUsageSystemWakeup  PROGMEM = OSC;
const uint8_t usgtypUsageSystemContextMenu  PROGMEM = OSC;
const uint8_t usgtypUsageSystemMainMenu  PROGMEM = OSC;
const uint8_t usgtypUsageSystemAppMenu  PROGMEM = OSC;
const uint8_t usgtypUsageSystemMenuHelp  PROGMEM = OSC;
const uint8_t usgtypUsageSystemMenuExit  PROGMEM = OSC;
const uint8_t usgtypUsageSystemMenuSelect  PROGMEM = OSC;
const uint8_t usgtypUsageSystemMenuRight  PROGMEM = RTC;
const uint8_t usgtypUsageSystemMenuLeft  PROGMEM = RTC;
const uint8_t usgtypUsageSystemMenuUp  PROGMEM = RTC;
const uint8_t usgtypUsageSystemMenuDown  PROGMEM = RTC;
const uint8_t usgtypUsageSystemColdRestart  PROGMEM = OSC;
const uint8_t usgtypUsageSystemWarmRestart  PROGMEM = OSC;
const uint8_t usgtypUsageDPadUp  PROGMEM = OOC;
const uint8_t usgtypUsageDPadDown  PROGMEM = OOC;
const uint8_t usgtypUsageDPadRight  PROGMEM = OOC;
const uint8_t usgtypUsageDPadLeft  PROGMEM = OOC;
const uint8_t usgtypUsageSystemDock  PROGMEM = OSC;
const uint8_t usgtypUsageSystemUndock  PROGMEM = OSC;
const uint8_t usgtypUsageSystemSetup  PROGMEM = OSC;
const uint8_t usgtypUsageSystemBreak  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDebuggerBreak  PROGMEM = OSC;
const uint8_t usgtypUsageApplicationBreak  PROGMEM = OSC;
const uint8_t usgtypUsageApplicationDebuggerBreak  PROGMEM = OSC;
const uint8_t usgtypUsageSystemSpeakerMute  PROGMEM = OSC;
const uint8_t usgtypUsageSystemHibernate  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayInvert  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayInternal  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayExternal  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayBoth  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayDual  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayToggleIntExt  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplaySwapPriSec  PROGMEM = OSC;
const uint8_t usgtypUsageSystemDisplayLCDAutoscale  PROGMEM = OSC;

// Simulation Controls Page
// const uint8_t usgtypUsageFlightSimulationDevice  PROGMEM = "Flight Simu Dev";
// const uint8_t usgtypUsageAutomobileSimulationDevice  PROGMEM = "Auto Simu Dev";
// const uint8_t usgtypUsageTankSimulationDevice  PROGMEM = "Tank Simu Dev";
// const uint8_t usgtypUsageSpaceshipSimulationDevice  PROGMEM = "Space Simu Dev";
// const uint8_t usgtypUsageSubmarineSimulationDevice  PROGMEM = "Subm Simu Dev";
// const uint8_t usgtypUsageSailingSimulationDevice  PROGMEM = "Sail Simu Dev";
// const uint8_t usgtypUsageMotocicleSimulationDevice  PROGMEM = "Moto Simu Dev";
// const uint8_t usgtypUsageSportsSimulationDevice  PROGMEM = "Sport Simu Dev";
// const uint8_t usgtypUsageAirplaneSimulationDevice  PROGMEM = "Airp Simu Dev";
// const uint8_t usgtypUsageHelicopterSimulationDevice  PROGMEM = "Heli Simu Dev";
// const uint8_t usgtypUsageMagicCarpetSimulationDevice  PROGMEM = "Magic Carpet Simu Dev";
// const uint8_t usgtypUsageBicycleSimulationDevice  PROGMEM = "Bike Simu Dev";
// const uint8_t usgtypUsageFlightControlStick  PROGMEM = "Flight Ctrl Stick";
// const uint8_t usgtypUsageFlightStick  PROGMEM = "Flight Stick";
// const uint8_t usgtypUsageCyclicControl  PROGMEM = "Cyclic Ctrl";
// const uint8_t usgtypUsageCyclicTrim  PROGMEM = "Cyclic Trim";
// const uint8_t usgtypUsageFlightYoke  PROGMEM = "Flight Yoke";
// const uint8_t usgtypUsageTrackControl  PROGMEM = "Track Ctrl";
// const uint8_t usgtypUsageAileron  PROGMEM = "Aileron";
// const uint8_t usgtypUsageAileronTrim  PROGMEM = "Aileron Trim";
// const uint8_t usgtypUsageAntiTorqueControl  PROGMEM = "Anti-Torque Ctrl";
// const uint8_t usgtypUsageAutopilotEnable  PROGMEM = "Autopilot Enable";
// const uint8_t usgtypUsageChaffRelease  PROGMEM = "Chaff Release";
// const uint8_t usgtypUsageCollectiveControl  PROGMEM = "Collective Ctrl";
// const uint8_t usgtypUsageDiveBrake  PROGMEM = "Dive Brake";
// const uint8_t usgtypUsageElectronicCountermeasures  PROGMEM = "El Countermeasures";
// const uint8_t usgtypUsageElevator  PROGMEM = "Elevator";
// const uint8_t usgtypUsageElevatorTrim  PROGMEM = "Elevator Trim";
// const uint8_t usgtypUsageRudder  PROGMEM = "Rudder";
// const uint8_t usgtypUsageThrottle  PROGMEM = "Throttle";
// const uint8_t usgtypUsageFlightCommunications  PROGMEM = "Flight Comm";
// const uint8_t usgtypUsageFlareRelease  PROGMEM = "Flare Release";
// const uint8_t usgtypUsageLandingGear  PROGMEM = "Landing Gear";
// const uint8_t usgtypUsageToeBrake  PROGMEM = "Toe Brake";
// const uint8_t usgtypUsageTrigger  PROGMEM = "Trigger";
// const uint8_t usgtypUsageWeaponsArm  PROGMEM = "Weapons Arm";
// const uint8_t usgtypUsageWeaponsSelect  PROGMEM = "Weapons Sel";
// const uint8_t usgtypUsageWingFlaps  PROGMEM = "Wing Flaps";
// const uint8_t usgtypUsageAccelerator  PROGMEM = "Accel";
// const uint8_t usgtypUsageBrake  PROGMEM = "Brake";
// const uint8_t usgtypUsageClutch  PROGMEM = "Clutch";
// const uint8_t usgtypUsageShifter  PROGMEM = "Shifter";
// const uint8_t usgtypUsageSteering  PROGMEM = "Steering";
// const uint8_t usgtypUsageTurretDirection  PROGMEM = "Turret Dir";
// const uint8_t usgtypUsageBarrelElevation  PROGMEM = "Barrel Ele";
// const uint8_t usgtypUsageDivePlane  PROGMEM = "Dive Plane";
// const uint8_t usgtypUsageBallast  PROGMEM = "Ballast";
// const uint8_t usgtypUsageBicycleCrank  PROGMEM = "Bicycle Crank";
// const uint8_t usgtypUsageHandleBars  PROGMEM = "Handle Bars";
// const uint8_t usgtypUsageFrontBrake  PROGMEM = "Front Brake";
// const uint8_t usgtypUsageRearBrake  PROGMEM = "Rear Brake";

// VR Controls Page
// const uint8_t usgtypUsageBelt  PROGMEM = "Belt";
// const uint8_t usgtypUsageBodySuit  PROGMEM = "Body Suit";
// const uint8_t usgtypUsageFlexor  PROGMEM = "Flexor";
// const uint8_t usgtypUsageGlove  PROGMEM = "Glove";
// const uint8_t usgtypUsageHeadTracker  PROGMEM = "Head Track";
// const uint8_t usgtypUsageHeadMountedDisplay  PROGMEM = "Head Disp";
// const uint8_t usgtypUsageHandTracker  PROGMEM = "Hand Track";
// const uint8_t usgtypUsageOculometer  PROGMEM = "Oculometer";
// const uint8_t usgtypUsageVest  PROGMEM = "Vest";
// const uint8_t usgtypUsageAnimatronicDevice  PROGMEM = "Animat Dev";
// const uint8_t usgtypUsageStereoEnable  PROGMEM = "Stereo Enbl";
// const uint8_t usgtypUsageDisplayEnable  PROGMEM = "Display Enbl";

// // Sport Controls Page
// const uint8_t usgtypUsageBaseballBat  PROGMEM = "Baseball Bat";
// const uint8_t usgtypUsageGolfClub  PROGMEM = "Golf Club";
// const uint8_t usgtypUsageRowingMachine  PROGMEM = "Rowing Mach";
// const uint8_t usgtypUsageTreadmill  PROGMEM = "Treadmill";
// const uint8_t usgtypUsageOar  PROGMEM = "Oar";
// const uint8_t usgtypUsageSlope  PROGMEM = "Slope";
// const uint8_t usgtypUsageRate  PROGMEM = "Rate";
// const uint8_t usgtypUsageStickSpeed  PROGMEM = "Stick Speed";
// const uint8_t usgtypUsageStickFaceAngle  PROGMEM = "Stick Face Ang";
// const uint8_t usgtypUsageStickHeelToe  PROGMEM = "Stick Heel/Toe";
// const uint8_t usgtypUsageStickFollowThough  PROGMEM = "Stick Flw Thru";
// const uint8_t usgtypUsageStickTempo  PROGMEM = "Stick Tempo";
// const uint8_t usgtypUsageStickType  PROGMEM = "Stick Type";
// const uint8_t usgtypUsageStickHeight  PROGMEM = "Stick Hght";
// const uint8_t usgtypUsagePutter  PROGMEM = "Putter";
// const uint8_t usgtypUsage1Iron  PROGMEM = "1 Iron";
// const uint8_t usgtypUsage2Iron  PROGMEM = "2 Iron";
// const uint8_t usgtypUsage3Iron  PROGMEM = "3 Iron";
// const uint8_t usgtypUsage4Iron  PROGMEM = "4 Iron";
// const uint8_t usgtypUsage5Iron  PROGMEM = "5 Iron";
// const uint8_t usgtypUsage6Iron  PROGMEM = "6 Iron";
// const uint8_t usgtypUsage7Iron  PROGMEM = "7 Iron";
// const uint8_t usgtypUsage8Iron  PROGMEM = "8 Iron";
// const uint8_t usgtypUsage9Iron  PROGMEM = "9 Iron";
// const uint8_t usgtypUsage10Iron  PROGMEM = "10 Iron";
// const uint8_t usgtypUsage11Iron  PROGMEM = "11 Iron";
// const uint8_t usgtypUsageSandWedge  PROGMEM = "Sand Wedge";
// const uint8_t usgtypUsageLoftWedge  PROGMEM = "Loft Wedge";
// const uint8_t usgtypUsagePowerWedge  PROGMEM = "Pwr Wedge";
// const uint8_t usgtypUsage1Wood  PROGMEM = "1 Wood";
// const uint8_t usgtypUsage3Wood  PROGMEM = "3 Wood";
// const uint8_t usgtypUsage5Wood  PROGMEM = "5 Wood";
// const uint8_t usgtypUsage7Wood  PROGMEM = "7 Wood";
// const uint8_t usgtypUsage9Wood  PROGMEM = "9 Wood";

// Game Controls Page
// const uint8_t usgtypUsage3DGameController  PROGMEM = "3D Game Ctrl";
// const uint8_t usgtypUsagePinballDevice  PROGMEM = "Pinball Dev";
// const uint8_t usgtypUsageGunDevice  PROGMEM = "Gun Dev";
// const uint8_t usgtypUsagePointOfView  PROGMEM = "POV";
// const uint8_t usgtypUsageTurnRightLeft  PROGMEM = "Turn Right Left";
// const uint8_t usgtypUsagePitchForwardBackward  PROGMEM = "Pitch Fwd/Back";
// const uint8_t usgtypUsageRollRightLeft  PROGMEM = "Roll Right/Left";
// const uint8_t usgtypUsageMoveRightLeft  PROGMEM = "Move Right/Left";
// const uint8_t usgtypUsageMoveForwardBackward  PROGMEM = "Move Fwd/Back";
// const uint8_t usgtypUsageMoveUpDown  PROGMEM = "Move Up/Down";
// const uint8_t usgtypUsageLeanRightLeft  PROGMEM = "Lean Right/Left";
// const uint8_t usgtypUsageLeanForwardBackward  PROGMEM = "Lean Fwd/Back";
// const uint8_t usgtypUsageHeightOfPOV  PROGMEM = "Height of POV";
// const uint8_t usgtypUsageFlipper  PROGMEM = "Flipper";
// const uint8_t usgtypUsageSecondaryFlipper  PROGMEM = "Second Flipper";
// const uint8_t usgtypUsageBump  PROGMEM = "Bump";
// const uint8_t usgtypUsageNewGame  PROGMEM = "New Game";
// const uint8_t usgtypUsageShootBall  PROGMEM = "Shoot Ball";
// const uint8_t usgtypUsagePlayer  PROGMEM = "Player";
// const uint8_t usgtypUsageGunBolt  PROGMEM = "Gun Bolt";
// const uint8_t usgtypUsageGunClip  PROGMEM = "Gun Clip";
// const uint8_t usgtypUsageGunSelector  PROGMEM = "Gun Sel";
// const uint8_t usgtypUsageGunSingleShot  PROGMEM = "Gun Sngl Shot";
// const uint8_t usgtypUsageGunBurst  PROGMEM = "Gun Burst";
// const uint8_t usgtypUsageGunAutomatic  PROGMEM = "Gun Auto";
// const uint8_t usgtypUsageGunSafety  PROGMEM = "Gun Safety";
// const uint8_t usgtypUsageGamepadFireJump  PROGMEM = "Gamepad Fire/Jump";
// const uint8_t usgtypUsageGamepadTrigger  PROGMEM = "Gamepad Trig";

// Generic Device Controls Page
// const uint8_t usgtypUsageBatteryStrength  PROGMEM = "Bat Strength";
// const uint8_t usgtypUsageWirelessChannel  PROGMEM = "Wireless Ch";
// const uint8_t usgtypUsageWirelessID  PROGMEM = "Wireless ID";
// const uint8_t usgtypUsageDiscoverWirelessControl  PROGMEM = "Discover Wireless Ctrl";
// const uint8_t usgtypUsageSecurityCodeCharEntered  PROGMEM = "Sec Code Char Entrd";
// const uint8_t usgtypUsageSecurityCodeCharErased  PROGMEM = "Sec Code Char Erased";
// const uint8_t usgtypUsageSecurityCodeCleared  PROGMEM = "Sec Code Cleared";

// LED Page
// const uint8_t usgtypUsageNumLock  PROGMEM = "Num Lock";
// const uint8_t usgtypUsageCapsLock  PROGMEM = "Caps Lock";
// const uint8_t usgtypUsageScrollLock  PROGMEM = "Scroll Lock";
// const uint8_t usgtypUsageCompose  PROGMEM = "Compose";
// const uint8_t usgtypUsageKana  PROGMEM = "Kana";
// const uint8_t usgtypUsagePower  PROGMEM = "Pwr";
// const uint8_t usgtypUsageShift  PROGMEM = "Shift";
// const uint8_t usgtypUsageDoNotDisturb  PROGMEM = "DND";
// const uint8_t usgtypUsageMute  PROGMEM = "Mute";
// const uint8_t usgtypUsageToneEnable  PROGMEM = "Tone Enbl";
// const uint8_t usgtypUsageHighCutFilter  PROGMEM = "High Cut Fltr";
// const uint8_t usgtypUsageLowCutFilter  PROGMEM = "Low Cut Fltr";
// const uint8_t usgtypUsageEqualizerEnable  PROGMEM = "Eq Enbl";
// const uint8_t usgtypUsageSoundFieldOn  PROGMEM = "Sound Field On";
// const uint8_t usgtypUsageSurroundOn  PROGMEM = "Surround On";
// const uint8_t usgtypUsageRepeat  PROGMEM = "Repeat";
// const uint8_t usgtypUsageStereo  PROGMEM = "Stereo";
// const uint8_t usgtypUsageSamplingRateDetect  PROGMEM = "Smpl Rate Detect";
// const uint8_t usgtypUsageSpinning  PROGMEM = "Spinning";
// const uint8_t usgtypUsageCAV  PROGMEM = "CAV";
// const uint8_t usgtypUsageCLV  PROGMEM = "CLV";
// const uint8_t usgtypUsageRecordingFormatDetect  PROGMEM = "Rec Format Detect";
// const uint8_t usgtypUsageOffHook  PROGMEM = "Off Hook";
// const uint8_t usgtypUsageRing  PROGMEM = "Ring";
// const uint8_t usgtypUsageMessageWaiting  PROGMEM = "Msg Wait";
// const uint8_t usgtypUsageDataMode  PROGMEM = "Data Mode";
// const uint8_t usgtypUsageBatteryOperation  PROGMEM = "Bat Op";
// const uint8_t usgtypUsageBatteryOK  PROGMEM = "Bat OK";
// const uint8_t usgtypUsageBatteryLow  PROGMEM = "Bat Low";
// const uint8_t usgtypUsageSpeaker  PROGMEM = "Speaker";
// const uint8_t usgtypUsageHeadSet  PROGMEM = "Head Set";
// const uint8_t usgtypUsageHold  PROGMEM = "Hold";
// const uint8_t usgtypUsageMicrophone  PROGMEM = "Mic";
// const uint8_t usgtypUsageCoverage  PROGMEM = "Coverage";
// const uint8_t usgtypUsageNightMode  PROGMEM = "Night Mode";
// const uint8_t usgtypUsageSendCalls  PROGMEM = "Send Calls";
// const uint8_t usgtypUsageCallPickup  PROGMEM = "Call Pickup";
// const uint8_t usgtypUsageConference  PROGMEM = "Conf";
// const uint8_t usgtypUsageStandBy  PROGMEM = "Stand-by";
// const uint8_t usgtypUsageCameraOn  PROGMEM = "Cam On";
// const uint8_t usgtypUsageCameraOff  PROGMEM = "Cam Off";
// const uint8_t usgtypUsageOnLine  PROGMEM = "On-Line";
// const uint8_t usgtypUsageOffLine  PROGMEM = "Off-Line";
// const uint8_t usgtypUsageBusy  PROGMEM = "Busy";
// const uint8_t usgtypUsageReady  PROGMEM = "Ready";
// const uint8_t usgtypUsagePaperOut  PROGMEM = "Paper Out";
// const uint8_t usgtypUsagePaperJam  PROGMEM = "Paper Jam";
// const uint8_t usgtypUsageRemote  PROGMEM = "Remote";
// const uint8_t usgtypUsageForward  PROGMEM = "Fwd";
// const uint8_t usgtypUsageReverse  PROGMEM = "Rev";
// const uint8_t usgtypUsageStop  PROGMEM = "Stop";
// const uint8_t usgtypUsageRewind  PROGMEM = "Rewind";
// const uint8_t usgtypUsageFastForward  PROGMEM = "Fast Fwd";
// const uint8_t usgtypUsagePlay  PROGMEM = "Play";
// const uint8_t usgtypUsagePause  PROGMEM = "Pause";
// const uint8_t usgtypUsageRecord  PROGMEM = "Rec";
// const uint8_t usgtypUsageError  PROGMEM = "Error";
// const uint8_t usgtypUsageSelectedIndicator  PROGMEM = "Usage Sel Ind";
// const uint8_t usgtypUsageInUseIndicator  PROGMEM = "Usage In Use Ind";
// const uint8_t usgtypUsageMultiModeIndicator  PROGMEM = "Usage Multi Mode Ind";
// const uint8_t usgtypUsageIndicatorOn  PROGMEM = "Ind On";
// const uint8_t usgtypUsageIndicatorFlash  PROGMEM = "Ind Flash";
// const uint8_t usgtypUsageIndicatorSlowBlink  PROGMEM = "Ind Slow Blk";
// const uint8_t usgtypUsageIndicatorFastBlink  PROGMEM = "Ind Fast Blk";
// const uint8_t usgtypUsageIndicatorOff  PROGMEM = "Ind Off";
// const uint8_t usgtypUsageFlashOnTime  PROGMEM = "Flash On Time";
// const uint8_t usgtypUsageSlowBlinkOnTime  PROGMEM = "Slow Blk On Time";
// const uint8_t usgtypUsageSlowBlinkOffTime  PROGMEM = "Slow Blk Off Time";
// const uint8_t usgtypUsageFastBlinkOnTime  PROGMEM = "Fast Blk On Time";
// const uint8_t usgtypUsageFastBlinkOffTime  PROGMEM = "Fast Blk Off Time";
// const uint8_t usgtypUsageIndicatorColor  PROGMEM = "Usage Ind Color";
// const uint8_t usgtypUsageIndicatorRed  PROGMEM = "Ind Red";
// const uint8_t usgtypUsageIndicatorGreen  PROGMEM = "Ind Green";
// const uint8_t usgtypUsageIndicatorAmber  PROGMEM = "Ind Amber";
// const uint8_t usgtypUsageGenericIndicator  PROGMEM = "Gen Ind";
// const uint8_t usgtypUsageSystemSuspend  PROGMEM = "Sys Suspend";
// const uint8_t usgtypUsageExternalPowerConnected  PROGMEM = "Ext Pwr Conn";

// Telephony Usage Page
// const uint8_t usgtypUsagePhone  PROGMEM = "Phone";
// const uint8_t usgtypUsageAnsweringMachine  PROGMEM = "Answ Mach";
// const uint8_t usgtypUsageMessageControls  PROGMEM = "Msg Ctrls";
// const uint8_t usgtypUsageHandset  PROGMEM = "Handset";
// const uint8_t usgtypUsageHeadset  PROGMEM = "Headset";
// const uint8_t usgtypUsageTelephonyKeyPad  PROGMEM = "Tel Key Pad";
// const uint8_t usgtypUsageProgrammableButton  PROGMEM = "Prog Button";
// const uint8_t usgtypUsageHookSwitch  PROGMEM = "Hook Sw";
// const uint8_t usgtypUsageFlash  PROGMEM = "Flash";
// const uint8_t usgtypUsageFeature  PROGMEM = "Feature";
//const uint8_t usgtypUsageHold  PROGMEM = "Hold";
// const uint8_t usgtypUsageRedial  PROGMEM = "Redial";
// const uint8_t usgtypUsageTransfer  PROGMEM = "Transfer";
// const uint8_t usgtypUsageDrop  PROGMEM = "Drop";
// const uint8_t usgtypUsagePark  PROGMEM = "Park";
// const uint8_t usgtypUsageForwardCalls  PROGMEM = "Fwd Calls";
// const uint8_t usgtypUsageAlternateFunction  PROGMEM = "Alt Func";
// const uint8_t usgtypUsageLine  PROGMEM = "Line";
// const uint8_t usgtypUsageSpeakerPhone  PROGMEM = "Spk Phone";
//const uint8_t usgtypUsageConference  PROGMEM = "Conference";
// const uint8_t usgtypUsageRingEnable  PROGMEM = "Ring Enbl";
// const uint8_t usgtypUsageRingSelect  PROGMEM = "Ring Sel";
// const uint8_t usgtypUsagePhoneMute  PROGMEM = "Phone Mute";
// const uint8_t usgtypUsageCallerID  PROGMEM = "Caller ID";
// const uint8_t usgtypUsageSend  PROGMEM = "Send";
// const uint8_t usgtypUsageSpeedDial  PROGMEM = "Speed Dial";
// const uint8_t usgtypUsageStoreNumber  PROGMEM = "Store Num";
// const uint8_t usgtypUsageRecallNumber  PROGMEM = "Recall Num";
// const uint8_t usgtypUsagePhoneDirectory  PROGMEM = "Phone Dir";
// const uint8_t usgtypUsageVoiceMail  PROGMEM = "Voice Mail";
// const uint8_t usgtypUsageScreenCalls  PROGMEM = "Screen Calls";
//const uint8_t usgtypUsageDoNotDisturb  PROGMEM = "Do Not Disturb";
// const uint8_t usgtypUsageMessage  PROGMEM = "Msg";
// const uint8_t usgtypUsageAnswerOnOff  PROGMEM = "Answer On/Off";
// const uint8_t usgtypUsageInsideDialTone  PROGMEM = "Inside Dial Tone";
// const uint8_t usgtypUsageOutsideDialTone  PROGMEM = "Outside Dial Tone";
// const uint8_t usgtypUsageInsideRingTone  PROGMEM = "Inside Ring Tone";
// const uint8_t usgtypUsageOutsideRingTone  PROGMEM = "Outside Ring Tone";
// const uint8_t usgtypUsagePriorityRingTone  PROGMEM = "Prior Ring Tone";
// const uint8_t usgtypUsageInsideRingback  PROGMEM = "Inside Ringback";
// const uint8_t usgtypUsagePriorityRingback  PROGMEM = "Priority Ringback";
// const uint8_t usgtypUsageLineBusyTone  PROGMEM = "Ln Busy Tone";
// const uint8_t usgtypUsageReorderTone  PROGMEM = "Reorder Tone";
// const uint8_t usgtypUsageCallWaitingTone  PROGMEM = "Call Wait Tone";
// const uint8_t usgtypUsageConfirmationTone1  PROGMEM = "Cnfrm Tone1";
// const uint8_t usgtypUsageConfirmationTone2  PROGMEM = "Cnfrm Tone2";
// const uint8_t usgtypUsageTonesOff  PROGMEM = "Tones Off";
// const uint8_t usgtypUsageOutsideRingback  PROGMEM = "Outside Ringback";
// const uint8_t usgtypUsageRinger  PROGMEM = "Ringer";
// const uint8_t usgtypUsagePhoneKey0  PROGMEM = "0";
// const uint8_t usgtypUsagePhoneKey1  PROGMEM = "1";
// const uint8_t usgtypUsagePhoneKey2  PROGMEM = "2";
// const uint8_t usgtypUsagePhoneKey3  PROGMEM = "3";
// const uint8_t usgtypUsagePhoneKey4  PROGMEM = "4";
// const uint8_t usgtypUsagePhoneKey5  PROGMEM = "5";
// const uint8_t usgtypUsagePhoneKey6  PROGMEM = "6";
// const uint8_t usgtypUsagePhoneKey7  PROGMEM = "7";
// const uint8_t usgtypUsagePhoneKey8  PROGMEM = "8";
// const uint8_t usgtypUsagePhoneKey9  PROGMEM = "9";
// const uint8_t usgtypUsagePhoneKeyStar  PROGMEM = "*";
// const uint8_t usgtypUsagePhoneKeyPound  PROGMEM = "#";
// const uint8_t usgtypUsagePhoneKeyA  PROGMEM = "A";
// const uint8_t usgtypUsagePhoneKeyB  PROGMEM = "B";
// const uint8_t usgtypUsagePhoneKeyC  PROGMEM = "C";
// const uint8_t usgtypUsagePhoneKeyD  PROGMEM = "D";

// Consumer Usage Page
const uint8_t usgtypUsageConsumerControl  PROGMEM = CA;
const uint8_t usgtypUsageNumericKeyPad  PROGMEM = NAry;
const uint8_t usgtypUsageProgrammableButton  PROGMEM = NAry;
const uint8_t usgtypUsageMicrophone  PROGMEM = CA;
const uint8_t usgtypUsageHeadphone  PROGMEM = CA;
const uint8_t usgtypUsageGraphicEqualizer  PROGMEM = CA;
const uint8_t usgtypUsagePlus10  PROGMEM = OSC;
const uint8_t usgtypUsagePlus100  PROGMEM = OSC;
const uint8_t usgtypUsageAMPM  PROGMEM = OSC;
const uint8_t usgtypUsagePower  PROGMEM = OOC;
const uint8_t usgtypUsageReset  PROGMEM = OSC;
const uint8_t usgtypUsageSleep  PROGMEM = OSC;
const uint8_t usgtypUsageSleepAfter  PROGMEM = OSC;
const uint8_t usgtypUsageSleepMode  PROGMEM = RTC;
const uint8_t usgtypUsageIllumination  PROGMEM = OOC;
const uint8_t usgtypUsageFunctionButtons  PROGMEM = OOC;
const uint8_t usgtypUsageMenu  PROGMEM = OSC;
const uint8_t usgtypUsageMenuPick  PROGMEM = OSC;
const uint8_t usgtypUsageMenuUp  PROGMEM = OSC;
const uint8_t usgtypUsageMenuDown  PROGMEM = OSC;
const uint8_t usgtypUsageMenuLeft  PROGMEM = OSC;
const uint8_t usgtypUsageMenuRight  PROGMEM = OSC;
const uint8_t usgtypUsageMenuEscape  PROGMEM = OSC;
const uint8_t usgtypUsageMenuValueIncrease  PROGMEM = OSC;
const uint8_t usgtypUsageMenuValueDecrease  PROGMEM = OSC;
const uint8_t usgtypUsageDataOnScreen  PROGMEM = OOC;
const uint8_t usgtypUsageClosedCaption  PROGMEM = OOC;
const uint8_t usgtypUsageClosedCaptionSelect  PROGMEM = OSC;
const uint8_t usgtypUsageVCRTV  PROGMEM = OOC;
const uint8_t usgtypUsageBroadcastMode  PROGMEM = OSC;
const uint8_t usgtypUsageSnapshot  PROGMEM = OSC;
const uint8_t usgtypUsageStill  PROGMEM = OSC;
const uint8_t usgtypUsageSelection  PROGMEM = NAry;
const uint8_t usgtypUsageAssignSelection  PROGMEM = OSC;
const uint8_t usgtypUsageModeStep  PROGMEM = OSC;
const uint8_t usgtypUsageRecallLast  PROGMEM = OSC;
const uint8_t usgtypUsageEnterChannel  PROGMEM = OSC;
const uint8_t usgtypUsageOrderMovie  PROGMEM = OSC;
const uint8_t usgtypUsageChannel  PROGMEM = LC;
const uint8_t usgtypUsageMediaSelection  PROGMEM = NAry;
const uint8_t usgtypUsageMediaSelectComputer  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectTV  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectWWW  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectDVD  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectTelephone  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectProgramGuide  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectVideoPhone  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectGames  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectMessages  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectCD  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectVCR  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectTuner  PROGMEM = Sel;
const uint8_t usgtypUsageQuit  PROGMEM = OSC;
const uint8_t usgtypUsageHelp  PROGMEM = OOC;
const uint8_t usgtypUsageMediaSelectTape  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectCable  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectSatellite  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectSecurity  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectHome  PROGMEM = Sel;
const uint8_t usgtypUsageMediaSelectCall  PROGMEM = Sel;
const uint8_t usgtypUsageChannelIncrement  PROGMEM = OSC;
const uint8_t usgtypUsageChannelDecrement  PROGMEM = OSC;
const uint8_t usgtypUsageMediaSelectSAP  PROGMEM = Sel;
const uint8_t usgtypUsageVCRPlus  PROGMEM = OSC;
const uint8_t usgtypUsageOnce  PROGMEM = OSC;
const uint8_t usgtypUsageDaily  PROGMEM = OSC;
const uint8_t usgtypUsageWeekly  PROGMEM = OSC;
const uint8_t usgtypUsageMonthly  PROGMEM = OSC;
const uint8_t usgtypUsagePlay  PROGMEM = OOC;
const uint8_t usgtypUsagePause  PROGMEM = OOC;
const uint8_t usgtypUsageRecord  PROGMEM = OOC;
const uint8_t usgtypUsageFastForward  PROGMEM = OOC;
const uint8_t usgtypUsageRewind  PROGMEM = OOC;
const uint8_t usgtypUsageScanNextTrack  PROGMEM = OSC;
const uint8_t usgtypUsageScanPreviousTrack  PROGMEM = OSC;
const uint8_t usgtypUsageStop  PROGMEM = OSC;
const uint8_t usgtypUsageEject  PROGMEM = OSC;
const uint8_t usgtypUsageRandomPlay  PROGMEM = OOC;
const uint8_t usgtypUsageSelectDisk  PROGMEM = NAry;
const uint8_t usgtypUsageEnterDisk  PROGMEM = MC;
const uint8_t usgtypUsageRepeat  PROGMEM = OSC;
const uint8_t usgtypUsageTracking  PROGMEM = LC;
const uint8_t usgtypUsageTrackNormal  PROGMEM = OSC;
const uint8_t usgtypUsageSlowTracking  PROGMEM = LC;
const uint8_t usgtypUsageFrameForward  PROGMEM = RTC;
const uint8_t usgtypUsageFrameBackwards  PROGMEM = RTC;
const uint8_t usgtypUsageMark  PROGMEM = OSC;
const uint8_t usgtypUsageClearMark  PROGMEM = OSC;
const uint8_t usgtypUsageRepeatFromMark  PROGMEM = OOC;
const uint8_t usgtypUsageReturnToMark  PROGMEM = OSC;
const uint8_t usgtypUsageSearchMarkForward  PROGMEM = OSC;
const uint8_t usgtypUsageSearchMarkBackwards  PROGMEM = OSC;
const uint8_t usgtypUsageCounterReset  PROGMEM = OSC;
const uint8_t usgtypUsageShowCounter  PROGMEM = OSC;
const uint8_t usgtypUsageTrackingIncrement  PROGMEM = RTC;
const uint8_t usgtypUsageTrackingDecrement  PROGMEM = RTC;
const uint8_t usgtypUsageStopEject  PROGMEM = OSC;
const uint8_t usgtypUsagePlayPause  PROGMEM = OSC;
const uint8_t usgtypUsagePlaySkip  PROGMEM = OSC;
const uint8_t usgtypUsageVolume  PROGMEM = LC;
const uint8_t usgtypUsageBalance  PROGMEM = LC;
const uint8_t usgtypUsageMute  PROGMEM = OOC;
const uint8_t usgtypUsageBass  PROGMEM = LC;
const uint8_t usgtypUsageTreble  PROGMEM = LC;
const uint8_t usgtypUsageBassBoost  PROGMEM = OOC;
const uint8_t usgtypUsageSurroundMode  PROGMEM = OSC;
const uint8_t usgtypUsageLoudness  PROGMEM = OOC;
const uint8_t usgtypUsageMPX  PROGMEM = OOC;
const uint8_t usgtypUsageVolumeIncrement  PROGMEM = RTC;
const uint8_t usgtypUsageVolumeDecrement  PROGMEM = RTC;
const uint8_t usgtypUsageSpeedSelect  PROGMEM = OSC;
const uint8_t usgtypUsagePlaybackSpeed  PROGMEM = NAry;
const uint8_t usgtypUsageStandardPlay  PROGMEM = Sel;
const uint8_t usgtypUsageLongPlay  PROGMEM = Sel;
const uint8_t usgtypUsageExtendedPlay  PROGMEM = Sel;
const uint8_t usgtypUsageSlow  PROGMEM = OSC;
const uint8_t usgtypUsageFanEnable  PROGMEM = OOC;
const uint8_t usgtypUsageFanSpeed  PROGMEM = LC;
const uint8_t usgtypUsageLightEnable  PROGMEM = OOC;
const uint8_t usgtypUsageLightIlluminationLevel  PROGMEM = LC;
const uint8_t usgtypUsageClimateControlEnable  PROGMEM = OOC;
const uint8_t usgtypUsageRoomTemperature  PROGMEM = LC;
const uint8_t usgtypUsageSecurityEnable  PROGMEM = OOC;
const uint8_t usgtypUsageFireAlarm  PROGMEM = OSC;
const uint8_t usgtypUsagePoliceAlarm  PROGMEM = OSC;
const uint8_t usgtypUsageProximity  PROGMEM = LC;
const uint8_t usgtypUsageMotion  PROGMEM = OSC;
const uint8_t usgtypUsageDuresAlarm  PROGMEM = OSC;
const uint8_t usgtypUsageHoldupAlarm  PROGMEM = OSC;
const uint8_t usgtypUsageMedicalAlarm  PROGMEM = OSC;
const uint8_t usgtypUsageBalanceRight  PROGMEM = RTC;
const uint8_t usgtypUsageBalanceLeft  PROGMEM = RTC;
const uint8_t usgtypUsageBassIncrement  PROGMEM = RTC;
const uint8_t usgtypUsageBassDecrement  PROGMEM = RTC;
const uint8_t usgtypUsageTrebleIncrement  PROGMEM = RTC;
const uint8_t usgtypUsageTrebleDecrement  PROGMEM = RTC;
const uint8_t usgtypUsageSpeakerSystem  PROGMEM = CL;
const uint8_t usgtypUsageChannelLeft  PROGMEM = CL;
const uint8_t usgtypUsageChannelRight  PROGMEM = CL;
const uint8_t usgtypUsageChannelCenter  PROGMEM = CL;
const uint8_t usgtypUsageChannelFront  PROGMEM = CL;
const uint8_t usgtypUsageChannelCenterFront  PROGMEM = CL;
const uint8_t usgtypUsageChannelSide  PROGMEM = CL;
const uint8_t usgtypUsageChannelSurround  PROGMEM = CL;
const uint8_t usgtypUsageChannelLowFreqEnhancement  PROGMEM = CL;
const uint8_t usgtypUsageChannelTop  PROGMEM = CL;
const uint8_t usgtypUsageChannelUnknown  PROGMEM = CL;
const uint8_t usgtypUsageSubChannel  PROGMEM = LC;
const uint8_t usgtypUsageSubChannelIncrement  PROGMEM = OSC;
const uint8_t usgtypUsageSubChannelDecrement  PROGMEM = OSC;
const uint8_t usgtypUsageAlternateAudioIncrement  PROGMEM = OSC;
const uint8_t usgtypUsageAlternateAudioDecrement  PROGMEM = OSC;
const uint8_t usgtypUsageApplicationLaunchButtons  PROGMEM = NAry;
const uint8_t usgtypUsageALLaunchButtonConfigTool  PROGMEM = Sel;
const uint8_t usgtypUsageALProgrammableButton  PROGMEM = Sel;
const uint8_t usgtypUsageALConsumerControlConfig  PROGMEM = Sel;
const uint8_t usgtypUsageALWordProcessor  PROGMEM = Sel;
const uint8_t usgtypUsageALTextEditor  PROGMEM = Sel;
const uint8_t usgtypUsageALSpreadsheet  PROGMEM = Sel;
const uint8_t usgtypUsageALGraphicsEditor  PROGMEM = Sel;
const uint8_t usgtypUsageALPresentationApp  PROGMEM = Sel;
const uint8_t usgtypUsageALDatabaseApp  PROGMEM = Sel;
const uint8_t usgtypUsageALEmailReader  PROGMEM = Sel;
const uint8_t usgtypUsageALNewsreader  PROGMEM = Sel;
const uint8_t usgtypUsageALVoicemail  PROGMEM = Sel;
const uint8_t usgtypUsageALContactsAddressBook  PROGMEM = Sel;
const uint8_t usgtypUsageALCalendarSchedule  PROGMEM = Sel;
const uint8_t usgtypUsageALTaskProjectManager  PROGMEM = Sel;
const uint8_t usgtypUsageALLogJournalTimecard  PROGMEM = Sel;
const uint8_t usgtypUsageALCheckbookFinance  PROGMEM = Sel;
const uint8_t usgtypUsageALCalculator  PROGMEM = Sel;
const uint8_t usgtypUsageALAVCapturePlayback  PROGMEM = Sel;
const uint8_t usgtypUsageALLocalMachineBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALLANWANBrow  PROGMEM = Sel;
const uint8_t usgtypUsageALInternetBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALRemoteNetISPConnect  PROGMEM = Sel;
const uint8_t usgtypUsageALNetworkConference  PROGMEM = Sel;
const uint8_t usgtypUsageALNetworkChat  PROGMEM = Sel;
const uint8_t usgtypUsageALTelephonyDialer  PROGMEM = Sel;
const uint8_t usgtypUsageALLogon  PROGMEM = Sel;
const uint8_t usgtypUsageALLogoff  PROGMEM = Sel;
const uint8_t usgtypUsageALLogonLogoff  PROGMEM = Sel;
const uint8_t usgtypUsageALTermLockScrSav  PROGMEM = Sel;
const uint8_t usgtypUsageALControlPannel  PROGMEM = Sel;
const uint8_t usgtypUsageALCommandLineProcessorRun  PROGMEM = Sel;
const uint8_t usgtypUsageALProcessTaskManager  PROGMEM = Sel;
const uint8_t usgtypUsageALSelectTaskApplication  PROGMEM = Sel;
const uint8_t usgtypUsageALNextTaskApplication  PROGMEM = Sel;
const uint8_t usgtypUsageALPreviousTaskApplication  PROGMEM = Sel;
const uint8_t usgtypUsageALPreemptiveHaltTaskApp  PROGMEM = Sel;
const uint8_t usgtypUsageALIntegratedHelpCenter  PROGMEM = Sel;
const uint8_t usgtypUsageALDocuments  PROGMEM = Sel;
const uint8_t usgtypUsageALThesaurus  PROGMEM = Sel;
const uint8_t usgtypUsageALDictionary  PROGMEM = Sel;
const uint8_t usgtypUsageALDesktop  PROGMEM = Sel;
const uint8_t usgtypUsageALSpellCheck  PROGMEM = Sel;
const uint8_t usgtypUsageALGrammarCheck  PROGMEM = Sel;
const uint8_t usgtypUsageALWirelessStatus  PROGMEM = Sel;
const uint8_t usgtypUsageALKeyboardLayout  PROGMEM = Sel;
const uint8_t usgtypUsageALVirusProtection  PROGMEM = Sel;
const uint8_t usgtypUsageALEncryption  PROGMEM = Sel;
const uint8_t usgtypUsageALScreenSaver  PROGMEM = Sel;
const uint8_t usgtypUsageALAlarms  PROGMEM = Sel;
const uint8_t usgtypUsageALClock  PROGMEM = Sel;
const uint8_t usgtypUsageALFileBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALPowerStatus  PROGMEM = Sel;
const uint8_t usgtypUsageALImageBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALAudioBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALMovieBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALDigitalRightsManager  PROGMEM = Sel;
const uint8_t usgtypUsageALDigitalWallet  PROGMEM = Sel;
const uint8_t usgtypUsageALInstantMessaging  PROGMEM = Sel;
const uint8_t usgtypUsageALOEMFeaturesBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALOEMHelp  PROGMEM = Sel;
const uint8_t usgtypUsageALOnlineCommunity  PROGMEM = Sel;
const uint8_t usgtypUsageALEntertainmentContentBrow  PROGMEM = Sel;
const uint8_t usgtypUsageALOnlineShoppingBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALSmartCardInfoHelp  PROGMEM = Sel;
const uint8_t usgtypUsageALMarketMonitorFinBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALCustomCorpNewsBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALOnlineActivityBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALResearchSearchBrowser  PROGMEM = Sel;
const uint8_t usgtypUsageALAudioPlayer  PROGMEM = Sel;
const uint8_t usgtypUsageGenericGUIAppControls  PROGMEM = NAry;
const uint8_t usgtypUsageACNew  PROGMEM = Sel;
const uint8_t usgtypUsageACOpen  PROGMEM = Sel;
const uint8_t usgtypUsageACClose  PROGMEM = Sel;
const uint8_t usgtypUsageACExit  PROGMEM = Sel;
const uint8_t usgtypUsageACMaximize  PROGMEM = Sel;
const uint8_t usgtypUsageACMinimize  PROGMEM = Sel;
const uint8_t usgtypUsageACSave  PROGMEM = Sel;
const uint8_t usgtypUsageACPrint  PROGMEM = Sel;
const uint8_t usgtypUsageACProperties  PROGMEM = Sel;
const uint8_t usgtypUsageACUndo  PROGMEM = Sel;
const uint8_t usgtypUsageACCopy  PROGMEM = Sel;
const uint8_t usgtypUsageACCut  PROGMEM = Sel;
const uint8_t usgtypUsageACPaste  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectAll  PROGMEM = Sel;
const uint8_t usgtypUsageACFind  PROGMEM = Sel;
const uint8_t usgtypUsageACFindAndReplace  PROGMEM = Sel;
const uint8_t usgtypUsageACSearch  PROGMEM = Sel;
const uint8_t usgtypUsageACGoto  PROGMEM = Sel;
const uint8_t usgtypUsageACHome  PROGMEM = Sel;
const uint8_t usgtypUsageACBack  PROGMEM = Sel;
const uint8_t usgtypUsageACForward  PROGMEM = Sel;
const uint8_t usgtypUsageACStop  PROGMEM = Sel;
const uint8_t usgtypUsageACRefresh  PROGMEM = Sel;
const uint8_t usgtypUsageACPreviousLink  PROGMEM = Sel;
const uint8_t usgtypUsageACNextLink  PROGMEM = Sel;
const uint8_t usgtypUsageACBookmarks  PROGMEM = Sel;
const uint8_t usgtypUsageACHistory  PROGMEM = Sel;
const uint8_t usgtypUsageACSubscriptions  PROGMEM = Sel;
const uint8_t usgtypUsageACZoomIn  PROGMEM = Sel;
const uint8_t usgtypUsageACZoomOut  PROGMEM = Sel;
const uint8_t usgtypUsageACZoom  PROGMEM = Sel;
const uint8_t usgtypUsageACFullScreenView  PROGMEM = Sel;
const uint8_t usgtypUsageACNormalView  PROGMEM = Sel;
const uint8_t usgtypUsageACViewToggle  PROGMEM = Sel;
const uint8_t usgtypUsageACScrollUp  PROGMEM = Sel;
const uint8_t usgtypUsageACScrollDown  PROGMEM = Sel;
const uint8_t usgtypUsageACScroll  PROGMEM = Sel;
const uint8_t usgtypUsageACPanLeft  PROGMEM = Sel;
const uint8_t usgtypUsageACPanRight  PROGMEM = Sel;
const uint8_t usgtypUsageACPan  PROGMEM = Sel;
const uint8_t usgtypUsageACNewWindow  PROGMEM = Sel;
const uint8_t usgtypUsageACTileHoriz  PROGMEM = Sel;
const uint8_t usgtypUsageACTileVert  PROGMEM = Sel;
const uint8_t usgtypUsageACFormat  PROGMEM = Sel;
const uint8_t usgtypUsageACEdit  PROGMEM = Sel;
const uint8_t usgtypUsageACBold  PROGMEM = Sel;
const uint8_t usgtypUsageACItalics  PROGMEM = Sel;
const uint8_t usgtypUsageACUnderline  PROGMEM = Sel;
const uint8_t usgtypUsageACStrikethrough  PROGMEM = Sel;
const uint8_t usgtypUsageACSubscript  PROGMEM = Sel;
const uint8_t usgtypUsageACSuperscript  PROGMEM = Sel;
const uint8_t usgtypUsageACAllCaps  PROGMEM = Sel;
const uint8_t usgtypUsageACRotate  PROGMEM = Sel;
const uint8_t usgtypUsageACResize  PROGMEM = Sel;
const uint8_t usgtypUsageACFlipHorizontal  PROGMEM = Sel;
const uint8_t usgtypUsageACFlipVertical  PROGMEM = Sel;
const uint8_t usgtypUsageACMirrorHorizontal  PROGMEM = Sel;
const uint8_t usgtypUsageACMirrorVertical  PROGMEM = Sel;
const uint8_t usgtypUsageACFontSelect  PROGMEM = Sel;
const uint8_t usgtypUsageACFontColor  PROGMEM = Sel;
const uint8_t usgtypUsageACFontSize  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyLeft  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyCenterH  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyRight  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyBlockH  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyTop  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyCenterV  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyBottom  PROGMEM = Sel;
const uint8_t usgtypUsageACJustifyBlockV  PROGMEM = Sel;
const uint8_t usgtypUsageACIndentDecrease  PROGMEM = Sel;
const uint8_t usgtypUsageACIndentIncrease  PROGMEM = Sel;
const uint8_t usgtypUsageACNumberedList  PROGMEM = Sel;
const uint8_t usgtypUsageACRestartNumbering  PROGMEM = Sel;
const uint8_t usgtypUsageACBulletedList  PROGMEM = Sel;
const uint8_t usgtypUsageACPromote  PROGMEM = Sel;
const uint8_t usgtypUsageACDemote  PROGMEM = Sel;
const uint8_t usgtypUsageACYes  PROGMEM = Sel;
const uint8_t usgtypUsageACNo  PROGMEM = Sel;
const uint8_t usgtypUsageACCancel  PROGMEM = Sel;
const uint8_t usgtypUsageACCatalog  PROGMEM = Sel;
const uint8_t usgtypUsageACBuyChkout  PROGMEM = Sel;
const uint8_t usgtypUsageACAddToCart  PROGMEM = Sel;
const uint8_t usgtypUsageACExpand  PROGMEM = Sel;
const uint8_t usgtypUsageACExpandAll  PROGMEM = Sel;
const uint8_t usgtypUsageACCollapse  PROGMEM = Sel;
const uint8_t usgtypUsageACCollapseAll  PROGMEM = Sel;
const uint8_t usgtypUsageACPrintPreview  PROGMEM = Sel;
const uint8_t usgtypUsageACPasteSpecial  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertMode  PROGMEM = Sel;
const uint8_t usgtypUsageACDelete  PROGMEM = Sel;
const uint8_t usgtypUsageACLock  PROGMEM = Sel;
const uint8_t usgtypUsageACUnlock  PROGMEM = Sel;
const uint8_t usgtypUsageACProtect  PROGMEM = Sel;
const uint8_t usgtypUsageACUnprotect  PROGMEM = Sel;
const uint8_t usgtypUsageACAttachComment  PROGMEM = Sel;
const uint8_t usgtypUsageACDeleteComment  PROGMEM = Sel;
const uint8_t usgtypUsageACViewComment  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectWord  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectSentence  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectParagraph  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectColumn  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectRow  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectTable  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectObject  PROGMEM = Sel;
const uint8_t usgtypUsageACRedoRepeat  PROGMEM = Sel;
const uint8_t usgtypUsageACSort  PROGMEM = Sel;
const uint8_t usgtypUsageACSortAscending  PROGMEM = Sel;
const uint8_t usgtypUsageACSortDescending  PROGMEM = Sel;
const uint8_t usgtypUsageACFilter  PROGMEM = Sel;
const uint8_t usgtypUsageACSetClock  PROGMEM = Sel;
const uint8_t usgtypUsageACViewClock  PROGMEM = Sel;
const uint8_t usgtypUsageACSelectTimeZone  PROGMEM = Sel;
const uint8_t usgtypUsageACEditTimeZone  PROGMEM = Sel;
const uint8_t usgtypUsageACSetAlarm  PROGMEM = Sel;
const uint8_t usgtypUsageACClearAlarm  PROGMEM = Sel;
const uint8_t usgtypUsageACSnoozeAlarm  PROGMEM = Sel;
const uint8_t usgtypUsageACResetAlarm  PROGMEM = Sel;
const uint8_t usgtypUsageACSyncronize  PROGMEM = Sel;
const uint8_t usgtypUsageACSendReceive  PROGMEM = Sel;
const uint8_t usgtypUsageACSendTo  PROGMEM = Sel;
const uint8_t usgtypUsageACReply  PROGMEM = Sel;
const uint8_t usgtypUsageACReplyAll  PROGMEM = Sel;
const uint8_t usgtypUsageACForwardMessage  PROGMEM = Sel;
const uint8_t usgtypUsageACSend  PROGMEM = Sel;
const uint8_t usgtypUsageACAttachFile  PROGMEM = Sel;
const uint8_t usgtypUsageACUpload  PROGMEM = Sel;
const uint8_t usgtypUsageACDownload  PROGMEM = Sel;
const uint8_t usgtypUsageACSetBorders  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertRow  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertColumn  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertFile  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertPicture  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertObject  PROGMEM = Sel;
const uint8_t usgtypUsageACInsertSymbol  PROGMEM = Sel;
const uint8_t usgtypUsageACSaveAndClose  PROGMEM = Sel;
const uint8_t usgtypUsageACRename  PROGMEM = Sel;
const uint8_t usgtypUsageACMerge  PROGMEM = Sel;
const uint8_t usgtypUsageACSplit  PROGMEM = Sel;
const uint8_t usgtypUsageACDistributeHorizontaly  PROGMEM = Sel;
const uint8_t usgtypUsageACDistributeVerticaly  PROGMEM = Sel;

// Digitaizers
// const uint8_t usgtypUsageDigitizer  PROGMEM = "Digitizer";
// const uint8_t usgtypUsagePen  PROGMEM = "Pen";
// const uint8_t usgtypUsageLightPen  PROGMEM = "Light Pen";
// const uint8_t usgtypUsageTouchScreen  PROGMEM = "Touch Scr";
// const uint8_t usgtypUsageTouchPad  PROGMEM = "Touch Pad";
// const uint8_t usgtypUsageWhiteBoard  PROGMEM = "White Brd";
// const uint8_t usgtypUsageCoordinateMeasuringMachine  PROGMEM = "Coord Meas Mach";
// const uint8_t usgtypUsage3DDigitizer  PROGMEM = "3D Dgtz";
// const uint8_t usgtypUsageStereoPlotter  PROGMEM = "Stereo Plot";
// const uint8_t usgtypUsageArticulatedArm  PROGMEM = "Art Arm";
// const uint8_t usgtypUsageArmature  PROGMEM = "Armature";
// const uint8_t usgtypUsageMultiplePointDigitizer  PROGMEM = "Multi Point Dgtz";
// const uint8_t usgtypUsageFreeSpaceWand  PROGMEM = "Free Space Wand";
// const uint8_t usgtypUsageStylus  PROGMEM = "Stylus";
// const uint8_t usgtypUsagePuck  PROGMEM = "Puck";
// const uint8_t usgtypUsageFinger  PROGMEM = "Finger";
// const uint8_t usgtypUsageTipPressure  PROGMEM = "Tip Press";
// const uint8_t usgtypUsageBarrelPressure  PROGMEM = "Brl Press";
// const uint8_t usgtypUsageInRange  PROGMEM = "In Range";
// const uint8_t usgtypUsageTouch  PROGMEM = "Touch";
// const uint8_t usgtypUsageUntouch  PROGMEM = "Untouch";
// const uint8_t usgtypUsageTap  PROGMEM = "Tap";
// const uint8_t usgtypUsageQuality  PROGMEM = "Qlty";
// const uint8_t usgtypUsageDataValid  PROGMEM = "Data Valid";
// const uint8_t usgtypUsageTransducerIndex  PROGMEM = "Transducer Ind";
// const uint8_t usgtypUsageTabletFunctionKeys  PROGMEM = "Tabl Func Keys";
// const uint8_t usgtypUsageProgramChangeKeys  PROGMEM = "Pgm Chng Keys";
//const uint8_t usgtypUsageBatteryStrength  PROGMEM = "Bat Strength";
// const uint8_t usgtypUsageInvert  PROGMEM = "Invert";
// const uint8_t usgtypUsageXTilt  PROGMEM = "X Tilt";
// const uint8_t usgtypUsageYTilt  PROGMEM = "Y Tilt";
// const uint8_t usgtypUsageAzimuth  PROGMEM = "Azimuth";
// const uint8_t usgtypUsageAltitude  PROGMEM = "Altitude";
// const uint8_t usgtypUsageTwist  PROGMEM = "Twist";
// const uint8_t usgtypUsageTipSwitch  PROGMEM = "Tip Sw";
// const uint8_t usgtypUsageSecondaryTipSwitch  PROGMEM = "Scnd Tip Sw";
// const uint8_t usgtypUsageBarrelSwitch  PROGMEM = "Brl Sw";
// const uint8_t usgtypUsageEraser  PROGMEM = "Eraser";
// const uint8_t usgtypUsageTabletPick  PROGMEM = "Tbl Pick";

// Alphanumeric Display Page
// const uint8_t usgtypUsageAlphanumericDisplay  PROGMEM = "Alphanum Disp";
// const uint8_t usgtypUsageBitmappedDisplay  PROGMEM = "Bmp Disp";
// const uint8_t usgtypUsageDisplayAttributesReport  PROGMEM = "Disp Attr Rpt";
// const uint8_t usgtypUsageASCIICharacterSet  PROGMEM = "ASCII chset";
// const uint8_t usgtypUsageDataReadBack  PROGMEM = "Data Rd Back";
// const uint8_t usgtypUsageFontReadBack  PROGMEM = "Fnt Rd Back";
// const uint8_t usgtypUsageDisplayControlReport  PROGMEM = "Disp Ctrl Rpt";
// const uint8_t usgtypUsageClearDisplay  PROGMEM = "Clr Disp";
//const uint8_t usgtypUsageDisplayEnable  PROGMEM = "Disp Enbl";
// const uint8_t usgtypUsageScreenSaverDelay  PROGMEM = "Scr Sav Delay";
// const uint8_t usgtypUsageScreenSaverEnable  PROGMEM = "Scr Sav Enbl";
// const uint8_t usgtypUsageVerticalScroll  PROGMEM = "V Scroll";
// const uint8_t usgtypUsageHorizontalScroll  PROGMEM = "H Scroll";
// const uint8_t usgtypUsageCharacterReport  PROGMEM = "Char Rpt";
// const uint8_t usgtypUsageDisplayData  PROGMEM = "Disp Data";
// const uint8_t usgtypUsageDisplayStatus  PROGMEM = "Disp Stat";
// const uint8_t usgtypUsageStatusNotReady  PROGMEM = "Stat !Ready";
// const uint8_t usgtypUsageStatusReady  PROGMEM = "Stat Ready";
// const uint8_t usgtypUsageErrorNotALoadableCharacter  PROGMEM = "Err Not Ld Char";
// const uint8_t usgtypUsageErrorFotDataCanNotBeRead  PROGMEM = "Fnt Data Rd Err";
// const uint8_t usgtypUsageCursorPositionReport  PROGMEM = "Cur Pos Rpt";
// const uint8_t usgtypUsageRow  PROGMEM = "Row";
// const uint8_t usgtypUsageColumn  PROGMEM = "Col";
// const uint8_t usgtypUsageRows  PROGMEM = "Rows";
// const uint8_t usgtypUsageColumns  PROGMEM = "Cols";
// const uint8_t usgtypUsageCursorPixelPosition  PROGMEM = "Cur Pix Pos";
// const uint8_t usgtypUsageCursorMode  PROGMEM = "Cur Mode";
// const uint8_t usgtypUsageCursorEnable  PROGMEM = "Cur Enbl";
// const uint8_t usgtypUsageCursorBlink  PROGMEM = "Cur Blnk";
// const uint8_t usgtypUsageFontReport  PROGMEM = "Fnt Rpt";
// const uint8_t usgtypUsageFontData  PROGMEM = "Fnt Data";
// const uint8_t usgtypUsageCharacterWidth  PROGMEM = "Char Wdth";
// const uint8_t usgtypUsageCharacterHeight  PROGMEM = "Char Hght";
// const uint8_t usgtypUsageCharacterSpacingHorizontal  PROGMEM = "Char Space H";
// const uint8_t usgtypUsageCharacterSpacingVertical  PROGMEM = "Char Space V";
// const uint8_t usgtypUsageUnicodeCharset  PROGMEM = "Unicode Char";
// const uint8_t usgtypUsageFont7Segment  PROGMEM = "Fnt 7-seg";
// const uint8_t usgtypUsage7SegmentDirectMap  PROGMEM = "7-seg map";
// const uint8_t usgtypUsageFont14Segment  PROGMEM = "Fnt 14-seg";
// const uint8_t usgtypUsage14SegmentDirectMap  PROGMEM = "14-seg map";
// const uint8_t usgtypUsageDisplayBrightness  PROGMEM = "Disp Bright";
// const uint8_t usgtypUsageDisplayContrast  PROGMEM = "Disp Cntrst";
// const uint8_t usgtypUsageCharacterAttribute  PROGMEM = "Char Attr";
// const uint8_t usgtypUsageAttributeReadback  PROGMEM = "Attr Readbk";
// const uint8_t usgtypUsageAttributeData  PROGMEM = "Attr Data";
// const uint8_t usgtypUsageCharAttributeEnhance  PROGMEM = "Char Attr Enh";
// const uint8_t usgtypUsageCharAttributeUnderline  PROGMEM = "Char Attr Undl";
// const uint8_t usgtypUsageCharAttributeBlink  PROGMEM = "Char Attr Blnk";
// const uint8_t usgtypUsageBitmapSizeX  PROGMEM = "Bmp Size X";
// const uint8_t usgtypUsageBitmapSizeY  PROGMEM = "Bmp Size Y";
// const uint8_t usgtypUsageBitDepthFormat  PROGMEM = "Bit Dpth Fmt";
// const uint8_t usgtypUsageDisplayOrientation  PROGMEM = "Disp Ornt";
// const uint8_t usgtypUsagePaletteReport  PROGMEM = "Pal Rpt";
// const uint8_t usgtypUsagePaletteDataSize  PROGMEM = "Pal Data Size";
// const uint8_t usgtypUsagePaletteDataOffset  PROGMEM = "Pal Data Off";
// const uint8_t usgtypUsagePaletteData  PROGMEM = "Pal Data";
// const uint8_t usgtypUsageBlitReport  PROGMEM = "Blit Rpt";
// const uint8_t usgtypUsageBlitRectangleX1  PROGMEM = "Blit Rect X1";
// const uint8_t usgtypUsageBlitRectangleY1  PROGMEM = "Blit Rect Y1";
// const uint8_t usgtypUsageBlitRectangleX2  PROGMEM = "Blit Rect X2";
// const uint8_t usgtypUsageBlitRectangleY2  PROGMEM = "Blit Rect Y2";
// const uint8_t usgtypUsageBlitData  PROGMEM = "Blit Data";
// const uint8_t usgtypUsageSoftButton  PROGMEM = "Soft Btn";
// const uint8_t usgtypUsageSoftButtonID  PROGMEM = "Soft Btn ID";
// const uint8_t usgtypUsageSoftButtonSide  PROGMEM = "Soft Btn Side";
// const uint8_t usgtypUsageSoftButtonOffset1  PROGMEM = "Soft Btn Off1";
// const uint8_t usgtypUsageSoftButtonOffset2  PROGMEM = "Soft Btn Off2";
// const uint8_t usgtypUsageSoftButtonReport  PROGMEM = "Soft Btn Rpt";

// Medical Instrument Page
// const uint8_t usgtypUsageMedicalUltrasound  PROGMEM = "Med Ultrasnd";
// const uint8_t usgtypUsageVCRAcquisition  PROGMEM = "VCR/Acq";
// const uint8_t usgtypUsageFreezeThaw  PROGMEM = "Freeze";
// const uint8_t usgtypUsageClipStore  PROGMEM = "Clip Store";
// const uint8_t usgtypUsageUpdate  PROGMEM = "Update";
// const uint8_t usgtypUsageNext  PROGMEM = "Next";
// const uint8_t usgtypUsageSave  PROGMEM = "Save";
// const uint8_t usgtypUsagePrint  PROGMEM = "Print";
// const uint8_t usgtypUsageMicrophoneEnable  PROGMEM = "Mic Enbl";
// const uint8_t usgtypUsageCine  PROGMEM = "Cine";
// const uint8_t usgtypUsageTransmitPower  PROGMEM = "Trans Pwr";
//const uint8_t usgtypUsageVolume  PROGMEM = "Vol";
// const uint8_t usgtypUsageFocus  PROGMEM = "Focus";
// const uint8_t usgtypUsageDepth  PROGMEM = "Depth";
// const uint8_t usgtypUsageSoftStepPrimary  PROGMEM = "Soft Stp-Pri";
// const uint8_t usgtypUsageSoftStepSecondary  PROGMEM = "Soft Stp-Sec";
// const uint8_t usgtypUsageDepthGainCompensation  PROGMEM = "Dpth Gain Comp";
// const uint8_t usgtypUsageZoomSelect  PROGMEM = "Zoom Sel";
// const uint8_t usgtypUsageZoomAdjust  PROGMEM = "Zoom Adj";
// const uint8_t usgtypUsageSpectralDopplerModeSelect  PROGMEM = "Spec Dop Mode Sel";
// const uint8_t usgtypUsageSpectralDopplerModeAdjust  PROGMEM = "Spec Dop Mode Adj";
// const uint8_t usgtypUsageColorDopplerModeSelect  PROGMEM = "Color Dop Mode Sel";
// const uint8_t usgtypUsageColorDopplerModeAdjust  PROGMEM = "Color Dop Mode Adj";
// const uint8_t usgtypUsageMotionModeSelect  PROGMEM = "Motion Mode Sel";
// const uint8_t usgtypUsageMotionModeAdjust  PROGMEM = "Motion Mode Adj";
// const uint8_t usgtypUsage2DModeSelect  PROGMEM = "2D Mode Sel";
// const uint8_t usgtypUsage2DModeAdjust  PROGMEM = "2D Mode Adj";
// const uint8_t usgtypUsageSoftControlSelect  PROGMEM = "Soft Ctrl Sel";
// const uint8_t usgtypUsageSoftControlAdjust  PROGMEM = "Soft Ctrl Adj";

//extern const char *usagePageTitles0[15];
//const char *usagePageTitles1;
//const char *genDesktopTitles0;
//const char *genDesktopTitles1;
//const char *genDesktopTitles2;
//const char *genDesktopTitles3;
//const char *genDesktopTitles4;
//const char *simuTitles0;
//const char *simuTitles1;
//const char *simuTitles2;
//const char *vrTitles0;
//const char *vrTitles1;
//const char *sportsCtrlTitles0;
//const char *sportsCtrlTitles1;
//const char *sportsCtrlTitles2;
//const char *gameTitles0;
//const char *gameTitles1;
//const char *genDevCtrlTitles;
//const char *ledTitles;
//const char *telTitles0;
//const char *telTitles1;
//const char *telTitles2;
//const char *telTitles3;
//const char *telTitles4;
//const char *telTitles5;
//const char *consTitles0;
//const char *consTitles1;
//const char *consTitles2;
//const char *consTitles3;
//const char *consTitles4;
//const char *consTitles5;
//const char *consTitles6;
//const char *consTitles7;
//const char *consTitles8;
//const char *consTitles9;
//const char *consTitlesA;
//const char *consTitlesB;
//const char *consTitlesC;
//const char *consTitlesD;
//const char *consTitlesE;
//const char *digitTitles0;
//const char *digitTitles1;
//const char *digitTitles2;
//const char *aplphanumTitles0;
//const char *aplphanumTitles1;
//const char *aplphanumTitles2;
//const char *medInstrTitles0;
//const char *medInstrTitles1;
//const char *medInstrTitles2;
//const char *medInstrTitles3;
//const char *medInstrTitles4;

#endif //__HIDUSAGESTR_H__
