#if !defined( __HIDUSAGEPAGE_H__)
#define  __HIDUSAGEPAGE_H__

#define GENERIC_DESKTOP_PAGE 0x01
#define SIMULATION_CONTROLS_PAGE 0x02
#define VR_CONTROLS_PAGE 0x03
#define SPORT_CONTROLS_PAGE 0x04
#define GAME_CONTROL_PAGGE 0x05
#define GENERIC_DEVICE_CONTROLS_PAGE 0x06
#define KEYBOARD_KEYPAD_PAGE 0x07
#define LED_PAGE 0x08
#define BUTTUN_PAGE 0x09
#define ORDINAL_PAGE 0x0A
#define TELEPHONY_DEVICE_PAGE 0x0B
#define CONSUMER_PAGE 0x0C
#define DIGITIZERS 0x0D
#define UNICODE_PAGE 0x10
#define ALPHANUMERIC_DISPLAY_PAGE 0x14
#define MEDICAL_INSTRUMENT_PAGE 0x40

#endif //__HIDUSAGEPAGE_H__
